export enum AUTH_ACTIONS {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTER = "REGISTER",
  REFRESH = "REFRESH",
  SET_TOKEN = "SET_TOKEN",
  SET_USER = "SET_USER",
  SET_LOADING = "SET_LOADING",
  SET_ASSETS_LOADING = "SET_ASSETS_LOADING",
}
